### ISSUE TITLE
Set custom efm_parameters before first start of EFM

### ISSUE THREAD

**Issue by michalgric** [EnterpriseDB/edb-ansible#125]
I would like to execute task efm_cluster_set_params.yml within efm_configure.yml before EFM first startup in setuo_efm role. 

With current version of setup_efm role, custom efm parameters for efm.properties are set after fist startup of EFM. This causes crash during the first start of EFM because in our environment it can't reach 8.8.8.8 ( ping.server.ip ) address.

As a solution suggest this change:

remove lines 142-144 from roles/setup_efm/tasks/setup_efm.yml

- name: Efm parameters settings
  include_tasks: efm_cluster_set_params.yml
  no_log: "{{ disable_logging }}"

add above code to roles/setup_efm/tasks/efm_configure.yml after "Update efm efm.properties file"  line 70

**Comment by vibhorkumar123** [comment]
Hi @michalgric, Welcome to the edb-ansible!

Thank you for your suggestion. I understand your use case and will fix this soon.

**Comment by michalgric** [comment]
Hi @vibhorkumar123  thank you for you quick response. I really appreciate  it.

**Comment by vibhorkumar123** [comment]
Fix has been merged in master
