### ISSUE TITLE
Verify EPAS 11 on: AWS, Azure and Google Cloud for: CentOS7, CentOS8, RHEL7 and RHEL8

### ISSUE THREAD

**Issue by dougortiz** [EnterpriseDB/edb-ansible#14]

**Comment by dougortiz** [comment]
EPAS 11 and 12 Failed on Cluster RHEL8 
![image](https://user-images.githubusercontent.com/63114888/96529616-a2eda180-1253-11eb-948a-5a6212fe9784.png)

**Comment by dougortiz** [comment]
Azure EPAS 11 Single Install Failure
![image](https://user-images.githubusercontent.com/63114888/96529680-d5979a00-1253-11eb-9a4d-45ef250a5460.png)

**Comment by dougortiz** [comment]
Azure - CentOS 7.7 EPAS 11 and 12 Single Install Fails:
![image](https://user-images.githubusercontent.com/63114888/96530779-24463380-1256-11eb-8207-2c58eee2bc43.png)

**Comment by dougortiz** [comment]
AWS - CentOS 7 EPAS 11 Single Install - Successful Installation

**Comment by dougortiz** [comment]
AWS - CentOS 8 EPAS 11 Cluster: 1 PEM Server and 1 Primary and 2 Standby Servers Install - Failed Installation:
![image](https://user-images.githubusercontent.com/63114888/96533294-a08f4580-125b-11eb-9017-823dd3184a8c.png)

**Comment by vibhorkumar123** [comment]
This is expected. EPAS 11 is not supported on CentOS8/RHEL8. README has information on the supported platform.
Do you think we should put a check in the roles?

**Comment by dougortiz** [comment]
AWS - CentOS8 and RHEL8 - EPAS 12 - Successful
Single Install and Cluster: 1 PEM Server, 1 Primary and 2 Standbys

**Comment by dougortiz** [comment]
Azure- CentOS8 - EPAS 12 - Successful
Azure - RHEL8 - EPAS 12 - Requires RedHat subscription - Successful
Single Install and Cluster: 1 PEM Server, 1 Primary and 2 Standbys

**Comment by dougortiz** [comment]
Google Cloud - CentOS8 - EPAS 12 - Successful
Google Cloud - RHEL8 - EPAS 12 - Requires RedHat subscription - Successful
Single Install and Cluster: 1 PEM Server, 1 Primary and 2 Standbys

**Comment by vibhorkumar123** [comment]
This issue is tested and completed
