### ISSUE TITLE
setup_repo role failing on CentOS8

### ISSUE THREAD

**Issue by julmon** [EnterpriseDB/edb-ansible#17]
Hi,

It seems `setup_repo` role fails on CentOS8:

```console
TASK [setup_repo : Install epel and EDB repo] *************************************************************************************
fatal: [primary-centos8.home.virt -> 192.168.122.33]: FAILED! => {"changed": false, "msg": "Failed to validate GPG signature for epel-release-8-8.el8.noarch"}
```

Ansible version is 2.9.13 (macos).

This issue looks related to this Ansible version: https://github.com/geerlingguy/ansible-role-repo-remi/pull/20

To get it working, we should download GPG key in a dedicated task before installing repo RPM, some examples here: https://github.com/ansible/ansible/issues/71634

This issue affects epel, PGDG ans EDB repositories setup.

Regards,

**Comment by vibhorkumar123** [comment]
Fix is merged. Thank you, @julmon!

Closing this issue.
