### ISSUE TITLE
pgpool2 issue

### ISSUE THREAD

**Issue by dougortiz** [EnterpriseDB/edb-ansible#176]
Issue when deploying in AWS EDB-RA-2, terraform 0.14.17 and ansible 2.10.6:

`fatal: [primary1]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'edb_devops.edb_postgres.pgpool2_nodes'. Error was a <class 'KeyError'>, original message: 'pgpool2'"}`

**Comment by jt-edb** [comment]
Hello,

Thank you. This is now fixed in `master` and `v3_3`. A new maintenance release -- 3.3.1 -- has been published on GitHub and Ansible Galaxy.

Closing this issue.
