### ISSUE TITLE
Set up Ansible to pull from local rpm repo?

### ISSUE THREAD

**Issue by DHorneDBA** [EnterpriseDB/edb-ansible#197]
Because of security reasons the server we plan on running our Ansible scripts from is not allowed to go to the internet to the yum repo for EDB. Currently we manually stage the repo locally and run our builds from there. Is there a way to point the setup_repo role to a local file based repo?

**Comment by jt-edb** [comment]
At the moment, there is no way to configure the `setup_repo` role for local repo access. Could you please share how do you manually clone the EDB repo, I'll see if we can update the role in that sense.

**Comment by CC-Hsu** [comment]
Hi, jt-edb,

We also have similar situation in our customers' environments.
Usually we use the following steps to bring EDB/PGDG YUM repository for offline use.
1) Download packaged tarball from https://repos.enterprisedb.com/
or utilize `reposync` to download repository content (usually for PGDG repo) and package the whole directory as a tarball
2) Bring the tarball to target offline environment, 
3) Start a simple HTTPD/Nginx service on a server (for example, running this service on PEM server before installation)
4) Uncompress the tarball to the directory
5) Edit repo file and point to the server IP start at step3

It would be great if `edb-ansible` can be enhanced to support local repository.

Best Regards.

**Comment by DHorneDBA** [comment]
> At the moment, there is no way to configure the `setup_repo` role for local repo access. Could you please share how do you manually clone the EDB repo, I'll see if we can update the role in that sense.

Hi, jt-edb,

We following almost exactly what CC-Hsu mentions in his response. We download the tarball from yum.enterprisedb.com and the untar on a local file server. The repo config on the server is then configured to point to that untar directory...

**Comment by jt-edb** [comment]
Thank you @CC-Hsu and @DHorneDBA. We will see how to add this feature.

**Comment by jt-edb** [comment]
Hi @CC-Hsu & @DHorneDBA,

Could you give a try to this PR: https://github.com/EnterpriseDB/edb-ansible/pull/205
