### ISSUE TITLE
Debian init_dbserver seems broken in 3.5.0

### ISSUE THREAD

**Issue by pgstef** [EnterpriseDB/edb-ansible#216]
Hi,

Just tried the new release (3.5.0) and it seems to be an issue with Debian support in `init_dbserver`:

```
TASK [edb_devops.edb_postgres.init_dbserver : Initialize database postgres service] ***
fatal: [u20pg-1]: FAILED! => {
   "changed":true,
   "cmd":"/usr/bin/pg_createcluster -s /var/run/postgresql 13 main -- ${PGSETUP_INITDB_OPTIONS} postgresql@13-main\n",
   "delta":"0:00:00.348565",
   "end":"2021-08-19 07:17:08.810019",
   "msg":"non-zero return code",
   "rc":1,
   "start":"2021-08-19 07:17:08.461454",
   "stderr":"initdb: error: too many command-line arguments (first is \"postgresql@13-main\")\nTry \"initdb --help\" for more information.\nError: initdb failed",
   "stderr_lines":[
      "initdb: error: too many command-line arguments (first is \"postgresql@13-main\")",
      "Try \"initdb --help\" for more information.",
      "Error: initdb failed"
   ],
   "stdout":"Creating new PostgreSQL cluster 13/main ...\n/usr/lib/postgresql/13/bin/initdb -D /var/lib/postgresql/13/main -k -A scram-sha-256 --encoding=UTF-8 --locale=C.UTF-8 --auth-local=peer --pwfile /dev/zero postgresql@13-main",
   "stdout_lines":[
      "Creating new PostgreSQL cluster 13/main ...",
      "/usr/lib/postgresql/13/bin/initdb -D /var/lib/postgresql/13/main -k -A scram-sha-256 --encoding=UTF-8 --locale=C.UTF-8 --auth-local=peer --pwfile /dev/zero postgresql@13-main"
   ]
}
```

It is pretty easy to check:
```bash
$ cat /etc/issue
Ubuntu 20.04.2 LTS \n \l

$ /usr/bin/pg_createcluster -s /var/run/postgresql 13 main -- ${PGSETUP_INITDB_OPTIONS} postgresql@13-main
Creating new PostgreSQL cluster 13/main ...
/usr/lib/postgresql/13/bin/initdb -D /var/lib/postgresql/13/main --auth-local peer --auth-host md5 postgresql@13-main
initdb: error: too many command-line arguments (first is "postgresql@13-main")
Try "initdb --help" for more information.
Error: initdb failed

$ /usr/lib/postgresql/13/bin/initdb -D /var/lib/postgresql/13/main --auth-local peer --auth-host md5 postgresql@13-main
initdb: error: too many command-line arguments (first is "postgresql@13-main")
Try "initdb --help" for more information.
```

My guess is that [this](https://github.com/EnterpriseDB/edb-ansible/commit/9c21ca2a2749f01c0a78d6c039d03e6ed0352228) commit isn't working the same way for `postgresql-*-setup` (on RedHat's) and `pg_createcluster` (on Debian's).

I'm not sure what to do to fix this. Reverting `roles/init_dbserver/tasks/pg_initdb.yml` leads to:

```
TASK [edb_devops.edb_postgres.init_dbserver : Enable and start systemd service] ***
fatal: [u20pg-1]: FAILED! => {"changed": false, "msg": "Unable to start service postgresql@13-main: Assertion failed on job for postgresql@13-main.service.\n"}
```

Many thanks in advance for your support and help,
Kind Regards

**Comment by vibhorkumar123** [comment]
Thank you for reporting this problem. We will look into this. Our Debian support is limited to few roles in the collections. Maybe this got missed due to the support we added multiple instances for RedHat flavor.

**Comment by vibhorkumar123** [comment]
Hi @pgstef, following is the patch:
https://github.com/EnterpriseDB/edb-ansible/pull/217
 Above should fix the issue.

**Comment by pgstef** [comment]
Hey @vibhorkumar123, thanks for the fix. Indeed, it seems to fix the mentionned error.

To be complete, I've also found some fix to multi-instance support in `setup_replication` and `manage_dbserver` for Debian.
Do you want a dedicated PR for that or could you add it to this one ?

* `roles/setup_replication/tasks/rm_replication.yml`: [L25] deb_cluster_name -> pg_instance_name
* `roles/manage_dbserver/vars/EPAS_Debian.yml`: [L37] deb_cluster_name -> pg_instance_name
* `roles/manage_dbserver/vars/PG_Debian.yml`: [L31] deb_cluster_name -> pg_instance_name

Thanks again

**Comment by vibhorkumar123** [comment]
Thank you for the confirmation @pgstef! 
It will be awesome if you can submit a PR for the fixes!

Thank you!

**Comment by pgstef** [comment]
@vibhorkumar123 , I'll make a PR for setup_replication and manage_dbserver fix.
install_dbserver multi-instance support hasn't been done yet so I'll perhaps keep it for another PR ;-)

**Comment by vibhorkumar123** [comment]
Thank you!
