### ISSUE TITLE
Add get-wal option to barman config templates

### ISSUE THREAD

**Issue by klando** [EnterpriseDB/edb-ansible#228]
barman does not accept to recover with option "--no-get-wal" if this config option is not set.
And `get-wal` is not useful in some scenarios so it's convenient to just pass the `--no-get-wal` by default in such case.

See attached patches:
[add-get-wal.tar.gz](https://github.com/EnterpriseDB/edb-ansible/files/7153312/add-get-wal.tar.gz)

**Comment by vibhorkumar123** [comment]
Hi @klando Can you please create a PR and share the changes?

-Vibhor

**Comment by vibhorkumar123** [comment]
We have added the patch in our new release 3.6.0

**Comment by klando** [comment]
Thank you for the commit!
