### ISSUE TITLE
EFM and VIP

### ISSUE THREAD

**Issue by rocket-spec** [EnterpriseDB/edb-ansible#258]
Is it possible to declare a VIP using the setup_efm role ?

```
...
virtual.ip=
virtual.ip.interface=
virtual.ip.prefix=
virtual.ip.single=true
...
```

**Comment by vibhorkumar123** [comment]
Yes. You can declare these parameters in `efm_parameters`
https://github.com/EnterpriseDB/edb-ansible/blob/54534e831ad0cceb419fdd870501ff4446500535/roles/setup_efm/defaults/main.yml#L60

**Comment by vibhorkumar123** [comment]
No further response from the user. Closing it
