### ISSUE TITLE
Is it possible to make `edb-ansible` to support DB upgrade operation?

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/edb-ansible#265]
Hi, Team,

As we perform more and more DB upgrade operations on primary DBs for our customers,
I feel that DB upgrade task might be possible to be performed with ansible.

Performing `pg_upgrade` on primary DBs is relatively easy, but standby DB `rsync` is more cumbersome.

If this task can be handled by edb-ansible playbook, it can greatly benefit all PGSQL/EPAS users.

Below is outline steps based on my experience, including some checks to prevent upgrade process failure.
 1) Check available disk spaces if not choosing hard-link mode
 2) Check DB default locale, user-defined tablespaces and WAL segment size (or leave it as parameters for users to setup)
 3) Check used extensions (or leave it as parameters for users to setup)
 4) Install newer version packages and necessary extensions in both primary/standby node
 5) Temporarily backup config files (including `postgresql.auto.conf`,'pg_hba.conf','pg_ident.conf',`standby.signal` file) inside `$PGDATA` in both primary/standby DB
 6) Initialized the newer version DB instance with apporpriate encoding/collation and WAL segment size on the primary server
 7) Provide essential `pg_hba.conf` content for upgrade process
 8) Perform `pg_upgrade` dry-run check on the primary DB node
 9) Perform `pg_upgrade` check on the primary DB node
10) Perform `rsync` dry-run check on the primary node to standby DB nodes: including new/old `$PGDATA` and all tablespace direcotries
11) Perform `rsync` operation on the primary node to standby DB nodes: including new/old `$PGDATA` and all tablespace direcotries
12) Restore config files to newer version `$PGDATA` directories in both primary/standby node (but `archive_command` and `restore_command` might be commented out and left for users to fixed)
13) Start the new primary DB instance
14) Start all new standby DB instances
15) Check `pg_stat_replication` status
16) Apply post-upgrade operations on the primary DB (`update_extensions.sql`, `delete_old_cluster.sh`, and `analyze_new_cluster.sh`)
17) (Optional) update `~/.pgsql_profile` or `~/.enterprisedb_profile` pointing to the newer version

In the above steps, all assume DB directory layout as follows
 - `$PGDATA` are separated by DB versions (`/pgdata/as12/data/`, `/var/lib/edb/as13/data/`, `/pgdata/12/data/`, `/var/lib/pgsql/13/data/` ,..etc)
 - `pg_wal` directory is not separated

And in the rsync step, I follow the documentation example https://www.postgresql.org/docs/14/pgupgrade.html
```
[postgres@primarydb ~]$ rsync --archive --delete --hard-links --size-only --no-inc-recursive --verbose --dry-run /pgdata/12 /pgdata/13 standbydb:/pgdata
[postgres@primarydb ~]$ rsync --archive --delete --hard-links --size-only --no-inc-recursive --verbose --dry-run /some_pg_tblspc/PG_12_201909212 /some_pg_tblspc/PG_13_202007201 standbydb:/some_pg_tblspc
```

Will edb-ansible team consider to add such feature?

Best Regards.

**Comment by vibhorkumar123** [comment]
Hi @CC-Hsu, It's in our roadmap. However, if you would like to contribute, we would really appreciate your contribution.

**Comment by shaktishikha** [comment]
@CC-Hsu This is available in our latest EDB-Ansible([binary-upgrade role](https://github.com/EnterpriseDB/edb-ansible/tree/main/roles/execute_binary_upgrade)) release.
