### ISSUE TITLE
Issues with fixed collection dependencies

### ISSUE THREAD

**Issue by stroobl** [EnterpriseDB/edb-ansible#286]
Hello,

There are some fixed dependencies on certain versions of community collections and ansible.posix in this collection. People installing the collection with recent Ansible versions will actually pull in older versions of the depended collection and that can cause issues. For example Ansible 4.10.0 comes with community.general 3.8.3, ansible.posix 1.3.0, community.crypto 1.9.8 and community.postgresql 1.6.0.
You'll miss out a lot of bugfixes and cause unexpected behaviour if you downgrade them while installing this collection. It would be good to use more relaxed version requirements in dependencies, for example community.postgresql '>=1.1.1'. All these collections come bundled with Ansible project if you install for example ansible==4.10.0 and will be upgraded when people install a newer Ansible version.

https://github.com/EnterpriseDB/edb-ansible/blob/master/galaxy.template.yml
dependencies:
  "community.postgresql": "1.1.1"
  "ansible.posix": "1.1.1"
  "community.general": "2.1.1"
  "community.crypto": "1.4.0"

**Comment by MichaelDBA** [comment]
Can you simplify what you said above?  Set out numbered steps to this correctly.  Thanks in advance.

**Comment by stroobl** [comment]
The dependencies in galaxy.yml are limited to old versions and should be reviewed...

**Comment by vibhorkumar123** [comment]
This has been fixed by @jt-edb. Closed PR is attached to the issue.

**Comment by stroobl** [comment]
Do you only support one specific ansible version to run this code? Because it doesn't make sense to put the dependency versions for ansible bundled collections hard coded to a single version if you don't.

**Comment by vibhorkumar123** [comment]
The main reason is that we had seen issues with the collections in the past due to changes made by the collection owner.  Therefore we decided to put a dependency to ensure people don't face challenges. If we don't be specific, we will solve issues with one version and break for other versions.
However, we are open to ideas, and if you have tested the collection with one version and want to submit the PR, please let us know.
