### ISSUE TITLE
Adding core dump setup to `install_dbserver` or `autotuning` roles

### ISSUE THREAD

**Issue by CC-Hsu** [EnterpriseDB/edb-ansible#301]
Hi, Team,

Sometimes it may be necessary to enable core dump feature for PGSQL/EPAS.

As far as I know, there are [steps available to enable core dump in the EPAS installation guide](https://www.enterprisedb.com/docs/epas/latest/epas_inst_linux/04_enabling_core_dump/), which involves `sysctl`, `ulimit` and SystemD unit file settings.

It may be great if `edb-ansible` can include this setup and allow users to choose whether to enable/disable core dump setup.

Best Regards.

**Comment by vibhorkumar123** [comment]
As per PR, we have already added this. Closing this issue
