### ISSUE TITLE
Deployment of EDB Product on RedHat 8 and CentOS 8.

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/edb-ansible#4]
Please enable the deployment of EDB Product on RedHat 8 and CentOS 8.

**Comment by vibhorkumar123** [comment]
Assigning to @dougortiz for testing

**Comment by dougortiz** [comment]
Receiving error:

![image](https://user-images.githubusercontent.com/63114888/95800495-7ff84600-0cc5-11eb-8f17-09e9788d9257.png)

**Comment by dougortiz** [comment]
@vibhorkumar123 - Testing on AWS - Branch name: "REL-1_0_1-456"

**Comment by vibhorkumar123** [comment]
This is fixed in your branch and REL-1_0_1. @dougortiz, you can try now.

**Comment by dougortiz** [comment]
Tested on AWS:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS8, CentOS7, RHEL8
EPAS 13
RHEL7 no longer available

**Comment by dougortiz** [comment]
Testing on Azure:
Experienced error enclosed on: Centos 8_1 and RHEL7.8
![image](https://user-images.githubusercontent.com/63114888/96189685-f471f580-0f0e-11eb-8849-91a876374eb5.png)

**Comment by dougortiz** [comment]
Testing on Azure:
Experienced error enclosed on: CentOS8_1 and RHEL8.2
![image](https://user-images.githubusercontent.com/63114888/96189778-22573a00-0f0f-11eb-9be4-ee3aaa8d1415.png)

**Comment by dougortiz** [comment]
Tested on Google Cloud:
Tested on Azure:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS7, CentOS8, RHEL7, RHEL8
Single Installation
EPAS 12

**Comment by vibhorkumar123** [comment]
Fixed and tested! The fix is available in REL-1_0_1
