### ISSUE TITLE
Support PostgreSQL 13

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/edb-ansible#5]
We would like to have ansible to deploy PostgreSQL 13 and EPAS 13 on the operating system

**Comment by vibhorkumar123** [comment]
Assigning to @dougortiz for testing

**Comment by dougortiz** [comment]
@vibhorkumar123  - PostgreSQL v12.4

![image](https://user-images.githubusercontent.com/63114888/95800975-da45d680-0cc6-11eb-8251-e4737744fa4e.png)

**Comment by dougortiz** [comment]
@vibhorkumar123 - Testing on AWS - Branch name: "REL-1_0_1-456"

**Comment by vibhorkumar123** [comment]
@dougortiz, Not sure I understand the problem here. It is expected output.

**Comment by dougortiz** [comment]
Tested on AWS:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS8, CentOS7, RHEL8
EPAS 13
RHEL7 no longer available

**Comment by dougortiz** [comment]
Tested on Azure:
PEM Server: 1, Primary: 1, Standby's: 2 - CentOS7, CentOS8, RHEL7, RHEL8
Single Installation: CentOS7, CentOS8, RHEL7, RHEL8
EPAS 13

**Comment by vibhorkumar123** [comment]
Fixed and tested. Available in REL-1_0_1
