### ISSUE TITLE
setup_repo - epel install failing

### ISSUE THREAD

**Issue by pgstef** [EnterpriseDB/edb-ansible#516]
Hi,

On a simple centos:7 docker container (for example), the `setup_repo: Install EPEL repo for EL7` task fails with the following error:

> "msg": "Failure downloading https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm, 'NoneType' object is not callable"

Sometimes it works, and sometimes it doesn't (using GH actions). Any idea that might help with this issue?

Many thanks in advance for your advice.
Kind regards

**Comment by hannahms** [comment]
Hi @pgstef,

We have experienced this issue as well, especially with the github runners. I looked into it and it appears to be an Ansible issue, specifically, the [newer versions of ansible-core](https://github.com/ansible/ansible/issues/79371). I see some suggestions to workaround/fix the issue, and I can work on implementing those into the github runners and testing workflow. I also see that the runners install multiple versions of python3 and ansible-core, so cleaning this up may help as well.

If you happen to have more of the error message, more specifically, any python output showing the traceback, that would be greatly appreciated to determine where exactly the connection error is occurring. 

Thank you for your feedback!

**Comment by pgstef** [comment]
Hi,

Thanks for the feedback.

Since I only see those issues with GH actions runners ([example](https://github.com/EnterpriseDB/pgbackrest-tests/actions/runs/4745631331/jobs/8429000254)), I unfortunately don't have a more detailed error message, sorry :-(

I'll try to run it locally and see if I can reproduce the issue, but I haven't seen it locally yet.

Kind Regards

**Comment by vibhorkumar123** [comment]
Closing it. If require we can open this issue.
