### ISSUE TITLE
Setup replication without replication slots failing

### ISSUE THREAD

**Issue by pgstef** [EnterpriseDB/edb-ansible#538]
Hi,

Setup replication without replication slots is currently failing due to [this](https://github.com/EnterpriseDB/edb-ansible/blob/master/roles/setup_replication/tasks/validate_setup_replication.yml#L52) check:

```
TASK [edb_devops.edb_postgres.setup_replication: Check if replication slots were created correctly] ***
fatal: [ro8pg-2]: FAILED! => {
    "assertion": "repslots_query_result.results[0].query_result|length == standby_node_info|length",
    "changed": false,
    "evaluated_to": false,
    "msg": "Replication did not create replication slots"
}
```

I guess the task is simply missing a `when: use_replication_slots`?

Kind Regards,

**Comment by pgstef** [comment]
FWIW, I had to use `use_validation: false` to be able to work without replication slots. It seems like the validate_setup_replication task is only working with replication slots. So maybe adding `when: use_replication_slots` to bypass that task would be a quick solution?

**Comment by hannahms** [comment]
Hi Stefan,

Thank you for pointing this out. I will work to add the `use_replication_slots: false` flag within the validation tasks where applicable.

Is this something you will need a new release for or do you pull directly from the repo?

Thank you!

**Comment by pgstef** [comment]
I've got a temporary fix so I can wait for the next release, no problem.

Thanks for having a look at this :-)
