### ISSUE TITLE
RockyLinux 9 support

### ISSUE THREAD

**Issue by pgstef** [EnterpriseDB/edb-ansible#551]
Hi,

Is there any plan to support RockyLinux 9? And if so, any date for it?

Many thanks in advance,
Kind Regards

**Comment by hannahms** [comment]
Hi there,

We do have plans to support RHEL9/Rocky9. It is currently planned for late September.

I appreciate your feedback, it is useful to keep in mind when prioritizing enhancements. 

Hope this helps,
Best regards

**Comment by pgstef** [comment]
Hi,

We'll soon have to check EPAS 16 beta 1 and PGE 16 beta 1 support for our tools (target for mid Sept) on the EDB supported platforms. Given my test suites are based on edb-ansible, it would be good to have Rock9 support by then.

Also, any ETA regarding Debian11 and Ubuntu 22.04?

I understand the more roles you have to support, the harder it becomes to add new platforms but maybe at least having install/init_dbserver would be a very good starting point.

Many thanks in advance,
Kind Regards

**Comment by hannahms** [comment]
Hi,

Support for Rocky9 has been added and will be included in an upcoming release scheduled this week.

We have previously ran into some issues with beta repositories in edb-ansible, but are still considering including given EPAS 16 beta releases.

Debian11 and Ubuntu22 are currently schedule for early November release. 

Thank you!
