### ISSUE TITLE
setup_replication create standby fails since 3.22.0

### ISSUE THREAD

**Issue by pgstef** [EnterpriseDB/edb-ansible#577]
Hi,

I didn't change anything in my playbooks and the `TASK [edb_devops.edb_postgres.setup_replication: Create standby]` now fails with the last version, complaining about `no pg_hba.conf entry for replication connection`.

See the error below:

```
default: TASK [edb_devops.edb_postgres.setup_replication : Create standby] **************
default: ASYNC FAILED on c7pg-2: jid=465520477595.2528
default: fatal: [c7pg-2]: FAILED! => {
   "ansible_job_id":"465520477595.2528",
   "changed":true,
   "cmd":"PGAPPNAME=c7pg-2 /usr/pgsql-16/bin/pg_basebackup -Fp -R -l standby --checkpoint=fast --wal-method=stream -D /var/lib/pgsql/16/main/data --username=repuser --host=172.18.0.2 --port=5432\n",
...
   "stderr":"pg_basebackup: error: connection to server at \"172.18.0.2\", port 5432 failed: FATAL:  no pg_hba.conf entry for replication connection from host \"172.18.0.3\", user \"repuser\", no encryption",
   "stderr_lines":[
      "pg_basebackup: error: connection to server at \"172.18.0.2\", port 5432 failed: FATAL:  no pg_hba.conf entry for replication connection from host \"172.18.0.3\", user \"repuser\", no encryption"
   ],
```

When I run the playbook against v3.21.0, it just works fine. I admit I doesn't really know where to look to solve this issue.
Have you changed something between 3.21.0 and now regarding setup_replication or pg_hba management?

Many thanks in advance for your help

**Comment by hannahms** [comment]
Hi there,

I am not able to replicate this issue, could you please provide more information?
