### ISSUE TITLE
PgBackRest backup to S3

### ISSUE THREAD

**Issue by Sagebati** [EnterpriseDB/edb-ansible#587]
Hi, 

I searched but found nothing,  is there a way configure pgbackrest for saving backups in a s3 bucket and not in the pgbackrest_server ?

**Comment by hannahms** [comment]
Hi there,

[Here is an example connecting pgBackRest to an s3 bucket](https://pgstef.github.io/2019/07/19/pgbackrest_s3_configuration.html). Here is the official documentation with information on backing up to an s3 bucket for [RHEL](https://pgbackrest.org/user-guide-rhel.html#s3-support) and [Debian](https://pgbackrest.org/user-guide.html#s3-support) and references to the various [s3 configuration parameters ](https://pgbackrest.org/configuration.html#section-repository/option-repo-s3-bucket)that may be useful.

Regards,
Hannah
