### ISSUE TITLE
Repmgr support in edb-ansible

### ISSUE THREAD

**Issue by vibhorkumar123** [EnterpriseDB/edb-ansible#65]
Add the support for repmgr in edb-ansible

**Comment by klando** [comment]
Hi @vibhorkumar123,
is this support for repmgr still in the roadmap ?
Tks,
Cédric

**Comment by vibhorkumar123** [comment]
Hi @klando, It is in our roadmap. However, we haven't made any progress yet in this direction. So if you think you can make some progress, your contribution will be greatly appreciated. 

Thank you,
Vibhor

**Comment by klando** [comment]
Yes, I already have some tasks here and there for that. I will assemble them.
I just need to figure how setup_replication, setup_pgpool2, setup_barman(server), setup_pgbouncer works already. To evaluate how to organize setup_repmgr ('cause if offers to setup from barman, or just work on existing replication, manage pgbouncer and so on).
If you already had some designs in mind please share: for exemple, should setup_repmgr replace setup_replication or work together ? I think the current collection does inspection to find primary/secondary, should setup_repmgr restore the cluster state from the inventory (i.e. this node 1 is primary, this node 2 is secondary) after a switchover occurs or just adapt itself and notify the primary in production is not the primary declared in the inventory ? ...

**Comment by vibhorkumar123** [comment]
Hi @klando, you would like to look at the setup_efm (EDB Failover Manager) and accordingly create a role for repmgr.
setup_efm would be able to give an idea how we should develop role for setup_repmgr.

**Comment by vibhorkumar123** [comment]
Closing this issue. Now we have support for repmgr in edb-ansible
